include("tests_GlobalConstantPattern.jl") 
include("tests_StructOfArraysPattern.jl") 
include("tests_SharedArraysPattern.jl") 
include("tests_MemoizationPattern.jl") 
include("tests_BarrierFunctionPattern.jl")
